[conf]
default-lang = "sk"

[sk]
annotation = "Anotácia"
university = "Slovenská technická univerzita v Bratislave"
faculty = "Fakulta informatiky a informačných technológií"
bachelor-thesis = "Bakalárska práca"
master-thesis = "Diplomová práca"
supervisor = "Vedúci práce"
study-program = "Študijný program"
study-field = "Študijný odbor"
workplace = "Miesto vypracovania"



[en]
annotation = "Annotation"
university = "Slovak University of Technology in Bratislava"
faculty = "Faculty of Informatics and Information Technologies"
bachelor-thesis = "Bachelor's thesis"
master-thesis = "Master's thesis"
supervisor = "Thesis supervisor"
study-program = "Study program"
study-field = "Study field"
workplace = "Training workplace"