#import "thesis-template/lib.typ": thesis
#import "@preview/wordometer:0.1.4": word-count, total-words

// for counting words
#show: word-count

#show: thesis.with(
  thesis-lang: "en", // For Slovak use "sk"
  thesis-type: "bp1", // bp1, bp2, dp1, dp2, dp3, etc.
  paper-size: "a4",
  evidence-number: "FIIT-XXXX-XXXXX",
  title: (en: "The title of the thesis", sk: "Názov práce"),
  author: "Janko Mrkvicka", // name with titles
  thesis-supervisor-name: "Ing. Enzo Gorlomi, PhD.", // name with titles
  study-program: (en: "Informatics", sk: "Informatika"),
  // input 'study-field' and 'workplace' parameters in language of your thesis (used only once in document)
  study-field: "9.2.1 Computer Science / 9.2.1 Informatika",
  workplace: "Institute of Computer ... / Ústav počítačového ...",
  date: (en: "2025, January", sk: "Január 2025"),
  assignment: "../assets/assignment.png", // relative path to assignment file
  bibliography: bibliography("refs.bib"),
  // parameter -- full: true -> show all references without citing
  bib-style: "ieee", // style alternative "iso-690-numeric", default: "ieee"
  // you still can underline links individually when set to false 
  underline-links: true,  // default true

  annotations: (
    en: [
      Annotation text. #underline("Size should be 150-200 words.")
      #lorem(150)
    ],
    sk: [
      Text anotácie. #underline("Dĺžka by mala byť 150-200 slov.")
      #lorem(150)
    ],
  ),

  acknowledgement: [
    Write your acknowledgement. #underline("Do not forget") to mention your
    thesis supervisor. 
    
    Napíšte svoje poďakovanie. #underline("Nezabudnite") spomenúť svojho vedúceho práce.
  ],

  // set to `none` or remove entirely if you do not want this present in document
  list-of-abbrev: [
    // NOTE: if not `none` the heading is present, just fill this table
      #table(
        // setup
        stroke: none,
        align: left,
        columns: 2,
        inset: (left: 0pt, right: 1em),
        row-gutter: 0.5em,
        // content
       [*API*], [Application Programming Interface],
       [*UI*], [User Interface],
       [*UX*], [User Experience],
       [*SDK*], [Software Development Kit],
       [*IDE*], [Integrated Development Environment],
       [*IoT*], [Internet of Things],
       [*VPN*], [Virtual Private Network],
       [*SEO*], [Search Engine Optimization],
       [*HTTP*], [HyperText Transfer Protocol],
       [*CSS*], [Cascading Style Sheets],
      )
  ],

  // the same thing applies to these lists, but they are autogenerated
  // true -> show, false -> do not show
  list-of-figures: true,
  list-of-tables: true,

  // appendices needs to be written here manually to not break other things (for now)
  appendices: [
    = Appendix A
    == Work Schedule in Winter Semester
    #figure(
      table(
        columns: 2,
        [*Semester week number *], [*Info*],
        [1],[#lorem(8)],
        [2],[#lorem(8)],
        [3],[#lorem(8)],
        [4],[#lorem(8)],
        [5],[#lorem(8)],
        [6],[#lorem(8)],
        [7],[#lorem(8)],
        [8],[#lorem(8)],
        [9],[#lorem(8)],
        [10],[#lorem(8)],
        [12],[#lorem(8)],
        [12],[#lorem(8)],
      ),
    )

    // need to manually write this for now, because numbering is off globally for appendix and it will break other things
    === A.1 Plan Evaluation
    #lorem(100)

    = Appendix B

    == Survey questions

    #lorem(50)

    #figure(
      image("assets/Test.svg")
    )

  ]
)
// counter reset
#counter(page).update(1)

// =============== HERE YOU CAN START WRITING YOUR THESIS ===============

= Introduction <sec:intro>
#lorem(100)

@tab:example shows example of table in this template. #lorem(10)

#figure(
  table(
    columns: 3,
    [], [*Col 1*], [*Col 2*],
    [Row 1],[Content], [Content],
    [Row 2],[Content], [Content]
  ),
  caption: [Example of a Table],
) <tab:example>

#lorem(20)

@fig:test-image shows test image.
#lorem(20)

#figure(
  image("assets/Test.svg", width: 50%),
  caption: [Test image]
) <fig:test-image>

== Typst equation showcase
 This is inline $f(x) = a dot x^2 + b dot x + c$ equation. You cannot number not reference inline equation.

This is an example of equation which have numbering and you can reference it.

Entropy:

$
  H(S) = sum_(n=1)^C -p_i dot log_2(p_i)
$ <eq:entropy>

Equation @eq:entropy shows how entropy is calculated. For math symbols check Typst documentation on math/symbols.

== Another Typst references

We explained this in @sec:intro.

This is a test cite @vaswani2023attentionneed.

This is a test cite of more than one reference @vaswani2023attentionneed @einstein2005albert @2008mpin.book.....N.

// you can remove this anytime, it is just for your information and testing for how many words are in this document (idk about accuracy, but seems good)
// the position in document does not alter the calculation so you can move it anywhere
#text(stroke: 0.3pt + red)[
  Bachelor thesis should have 40 standard pages (recommended). One standard page is defined as 1800 characters per page. This is calculated as 30 rows #sym.times 60 characters per row. You can also calculate it as \~250 words per standard page. This means that you need \~10,000 words for this document.

  There is total of #underline([#total-words / 10000]) words in this document to fullfil the requirements of the thesis. Note that there are so many words because of lorem ipsum text.
]

- Example of bulleted list
  - indented
    - more indented
      - even more
    - #lorem(4)
  - #lorem(4)
- #lorem(4)

+ Example of ordered list 
+ More
  + indented
    + even more
    + more 2
  + #lorem(4)
  + #lorem(4)
+ #lorem(4)

= Analysis
#lorem(100)

== History of Paperclips
#lorem(100)

=== Manufacturing Process
#lorem(100)

=== Innovations in Design
#lorem(100)

== Benefits of Origami
#lorem(100)

=== Stress-Relief Benefits
#lorem(100)

=== Environmental Impact
#lorem(100)

=== Artistic Applications
#lorem(100)

== Mysteries of Black Holes
#lorem(30)

=== Accretion Disks
#lorem(100)

== Recipes for Success
#lorem(100)

== Laws of Motion
#lorem(100)

=== Newtonian Mechanics
#lorem(50)

=== Relativity
#lorem(50)

=== Quantum Implications
#lorem(50)

=== Practical Applications
#lorem(50)

= Experimenting
#lorem(10)
@fig:test-image2 shows test image. #lorem(20)

#figure(
  image("assets/Test.svg", width: 50%),
  caption: [Second Test image]
) <fig:test-image2>

@tab:example2 shows example of table in this template. #lorem(10)

#figure(
  table(
    columns: 3,
    [], [*Col 1*], [*Col 2*],
    [Row 1],[Content], [Content],
    [Row 2],[Content], [Content]
  ),
  caption: [Example 2 of a Table],
) <tab:example2>

#lorem(100)

== Wonders of Jellyfish
#lorem(100)

= Evaluation

== Benefits of Duct Tape
#lorem(100)

== Secrets of Ancient Cartography
#lorem(100)

== Strategies for Surviving Sharknadoes
#lorem(100)

= Guidelines for users
#lorem(100)

= Conclusion
#lorem(100)

// ==== RESUME is present only in theses which are not written in Slovak/Czech language ====
// this code needs to be here to now show resume in table of contents (ToC) and also it makes writing resume much easier
#set heading(numbering: none, outlined: false)
= Resumé
#lorem(100)
