#import "thesis-template/lib.typ": thesis
#import "@preview/wordometer:0.1.4": word-count, total-words
// import preliminaries
#import "thesis-template/preliminaries/annotation.typ": annotations-content
#import "thesis-template/preliminaries/acknowledgement.typ": acknowledgement-content
#import "thesis-template/preliminaries/abbreviations.typ": abbreviations-content

// for counting words
#show: word-count

#show: thesis.with(
  thesis-lang: "en", // For Slovak use "sk"
  thesis-type: "bp1", // bp1, bp2, dp1, dp2, dp3, etc.
  paper-size: "a4",
  page-numbering-position: "center", // "book" or "center" (default: "center")
  evidence-number: "FIIT-XXXX-XXXXX",
  title: (en: "The title of the thesis", sk: "Názov práce"),
  author: "Janko Mrkvicka", // name with titles
  thesis-supervisor-name: "Ing. Enzo Gorlomi, PhD.", // name with titles

  // departmental-advisor == pedagogical supervisor == pedagogický vedúci
  // if you dont have additional supervisor set `departmental-advisor` to `none`
  departmental-advisor: "doc. Ing. Dominick DeCocco, PhD.", // name with titles
  study-program: (en: "Informatics", sk: "Informatika"),

  // input 'study-field' and 'workplace' parameters in language of your thesis (used only once in document)
  study-field: "9.2.1 Computer Science / 9.2.1 Informatika",
  workplace: "Institute of Computer ... / Ústav počítačového ...",
  date: (en: "2025, January", sk: "Január 2025"),

  // uncomment line below and enter relative path to assignment file which must be in `.pdf` format
  // assignment: "../assets/assignment.pdf",

  // parameter of bibliography function --- full: true -> show all references without citing
  bibliography: bibliography("refs.bib"),

  // style alternative "iso-690-numeric", default: "ieee"
  bib-style: "ieee",

  // you still can underline links individually when set to false
  underline-links: true, // default true

  annotations: (
    sk: annotations-content.at("sk"),
    en: annotations-content.at("en"),
  ),
  acknowledgement: (
    acknowledgement-content
  ),

  // set to `none` or remove entirely if you do not want this present in document
  // if not `none` the heading is present, just fill the table in "preliminaries/abbreviations.typ"
  list-of-abbrev: abbreviations-content,

  // the same thing applies to these lists, but they are autogenerated
  // true -> show, false -> do not show
  // default: true
  list-of-figures: true,
  list-of-tables: true,

  // appendices needs to be written here manually to not break other things (for now)
  appendices: [
    #counter(page).update(0)
    #counter(heading).update(0)

    #include "thesis-template/appendices/schedule.typ"

    #include "thesis-template/appendices/cd_rom.typ"

    #include "thesis-template/appendices/AI_use.typ"

    #include "thesis-template/appendices/appendix.typ"
  ],
)
// counter reset
#counter(page).update(1)

// =============== HERE YOU CAN START WRITING YOUR THESIS ===============
// it is recommended to use chapters as separate files for better organization

#include "thesis-template/chapters/introduction.typ"

#include "thesis-template/chapters/analysis.typ"

#include "thesis-template/chapters/evaluation.typ"

#include "thesis-template/chapters/related_work.typ"

#include "thesis-template/chapters/conclusion.typ"

// as well as Literature/References Resumé is not numbered
#set heading(numbering: none)
#include "thesis-template/chapters/resume.typ"
