#import "../lib.typ": page-break, thesis
#import "@preview/wordometer:0.1.4": total-words, word-count

#import "preliminaries/annotation.typ": annotations-content
#import "preliminaries/acknowledgement.typ": acknowledgement-content
#import "preliminaries/abbreviations.typ": abbreviations-content

// for counting words
#show: word-count

#show: thesis.with(
  thesis-lang: "en", // for Slovak, use "sk"
  thesis-type: "dp1", // bp1, bp2, dp1, dp2, dp3, etc.
  paper-size: "a4",
  page-numbering-position: "center", // "book" or "center" (default: "center")
  evidence-number: "FIIT-XXXXX-XXXXXX", // thesis ID number obtained from AIS
  title: (
    en: "The title of the thesis",
    sk: "Názov práce"
  ),
  author: "Bc. Antonio Margheriti", // "name surname" with titles in double quotes
  thesis-supervisor-name: "Ing. Enzo Gorlomi, PhD.", // "name surname" with titles in double quotes

  // departmental-advisor == pedagogical supervisor == pedagogický vedúci
  departmental-advisor: "doc. Ing. Dominick Decocco, PhD.", // "name surname" with titles in double quotes or `none` if you do not have additional supervisor

  study-program: (
    en: "Informatics",
    sk: "Informatika"
  ),

  // input 'study-field' and 'workplace' parameters in language of your thesis (used only once in document)
  study-field: "9.2.1 Computer Science / 9.2.1 Informatika",
  workplace: "Institute of Computer Engineering and Applied Informatics, FIIT STU, Bratislava",
  date: (en: "2026, May", sk: "Máj 2026"),

  // !!! uncomment line below and enter relative path to assignment file which must be in `.pdf` format
  // assignment: "../assets/assignment.pdf",

  // parameter of bibliography function --- full: true -> show all references without citing
  bibliography: bibliography("refs.bib"),

  // style alternative "iso-690-numeric" or "iso-690-author-date", default: "ieee"
  bib-style: "ieee",

  // you still can underline links individually when set to false
  underline-links: true, // default true

  annotations: (
    sk: annotations-content.at("sk"),
    en: annotations-content.at("en"),
  ),
  acknowledgement: (
    acknowledgement-content
  ),

  // set to `none` or remove entirely if you do not want this present in document
  // if not `none` the heading is present, just fill the table in "preliminaries/abbreviations.typ"
  list-of-abbrev: abbreviations-content,

  // the same principle applies to these lists, but they are autogenerated
  // true -> show, false -> do not show
  // default: true
  list-of-figures: true,
  list-of-tables: true,

  appendices: [
    // do not show figures from appendices in the list of figures/tables (enable at your will)
    #set figure(outlined: false)

    #include "appendices/schedule.typ"
    #include "appendices/cd_rom.typ"
    #include "appendices/AI_use.typ"
    #include "appendices/appendix.typ"
  ],
)
// counter reset
#counter(page).update(0)

// =============== HERE YOU CAN START WRITING YOUR THESIS ===============

// NOTES:

// it is recommended to use chapters as separate files for better organization
// each "chapter file" should contain only one 1st level heading

// `#page-break()` is a custom function that disables page numbering, inserts a page break and then enables page numbering back
// it still accepts parameters as the original `pagebreak()` function
// it defaults to book style values

#include "chapters/introduction.typ"
#include "chapters/analysis.typ"
#include "chapters/evaluation.typ"
#include "chapters/related_work.typ"
#include "chapters/conclusion.typ"

// as well as Literature/References, Resumé is not numbered
#set heading(numbering: none)
#include "chapters/resume.typ"
